title: Cybersecurity Articles
description: Find my Cybersecurity Articles here
author: Joseph Kilatya
theme: jekyll-theme-cayman

# Jekyll settings
markdown: kramdown
permalink: /:title/
exclude:
  - .gitignore
  - .git
  - node_modules

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
encoding: utf-8
future: false
show_drafts: false